config/routes.rb
WizeBuilding::Application.routes.draw do
  resources :ideas

  root :to => 'welcome#index'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  attr_accessible :text, :user_id, :title
  validates :text, :title, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def mobile_device?
    request.user_agent =~ /Mobile|webOS/
  end

  helper_method :mobile_device?

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  def index
    @ideas = Idea.all
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new(params[:idea])
    if @idea.save
      redirect_to ideas_path
    else
      render :new
    end
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])
    if @idea.update_attributes(params[:idea])
      redirect_to ideas_path
    else
      render :edit
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render 'mobile' if mobile_device?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    output = ''
    unless object.errors.blank?
      output = object.errors.full_messages.join(', ')
    end
    output
  end
end

app/views/ideas/_form.html.haml
.alert.alert-error= error_messages_for(@idea)
= form_for @idea do |f|
  =f.label :title
  =f.text_field :title

  =f.label :text
  =f.text_area :text, rows: 3
  =submit_tag 'Submit', class: 'btn btn-primary'

app/views/ideas/edit.html.haml
Edit Idea
= render 'form'

app/views/ideas/index.html.haml
%h3 We have these ideas
=link_to 'Add a new idea', new_idea_path
%ul
  -@ideas.each do |idea|
    %li
      = idea.text
      =link_to 'edit', edit_idea_path(idea.id)

app/views/ideas/new.html.haml
Create Idea
= render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title WizeBuilding
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} Wize Building
          .nav-collapse.collapse
            %p.navbar-text.pull-right
              Logged in as
              %a.navbar-link{:href => "#"} Username
            %ul.nav
              %li.active
                %a{:href => "#"} Home
              %li
                %a{:href => "#about"} About
              %li
                %a{:href => "#contact"} Contact
          / /.nav-collapse
    .container-fluid
      .row-fluid
        .container
          =yield
          =request.user_agent

app/views/welcome/index.html.haml
.span12
  .hero-unit
    %h1 Hello, world!
    %p This is a template for a simple marketing or informational website. It includes a large callout called the hero unit and three supporting pieces of content. Use it as a starting point to create something more unique.
    %p
      %a.btn.btn-primary.btn-large Learn more »
  .row-fluid
    .span4
      %h2 Idea Box
      %p What are you thinking??
      %p
        = link_to 'Idea Box', ideas_path
    / /span
    .span4
      %h2 Heading
      %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
      %p
        %a.btn{:href => "#"} View details »
    / /span
    .span4
      %h2 Heading
      %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
      %p
        %a.btn{:href => "#"} View details »
    / /span
  / /row
  .row-fluid
    .span4
      %h2 Heading
      %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
      %p
        %a.btn{:href => "#"} View details »
    / /span
    .span4
      %h2 Heading
      %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
      %p
        %a.btn{:href => "#"} View details »
    / /span
    .span4
      %h2 Heading
      %p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
      %p
        %a.btn{:href => "#"} View details »
    / /span
  / /row
/ /span
/ /row
%hr
  %footer
    %p © Company 2012
/ /.fluid-container

app/views/welcome/mobile.html.haml
You are using mobile
.well Option 1
.well Option 2